name: PracticeAISite
favicon: null
layout_spectrum: 0.31471
typography_spectrum: 0.54997
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafc'
    - '#a0b8e3'
    - '#6d7492'
    - '#4c4e63'
    - '#2c2937'
  brandStrength: 1
  lightness: 0.9220627585891634
  saturation: 0.9409481997136027
  rhythmicContrast: 0.2797662694938481
purpose: []
